apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay
  labels:
    app: cowsay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cowsay
  template:
    metadata:
      labels:
        app: cowsay
    spec:
      containers:
        - name: cowsay
          image: rg.fr-par.scw.cloud/bidouille/cowsay:latest
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cowsay
spec:
  type: NodePort
  selector:
    app: cowsay
  ports:
  - port: 8080
    name: http
